import type { Preset } from '../stores/use-preset-store.ts';

export const DEFAULT_PRESETS: Array<Preset> = [
  {
    id: 'preset-flat-beat',
    name: 'Flat Beat',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -15,
          transpose: -12,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 15,
          transpose: -12,
        },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 80, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.2, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 150,
        resonance: 25,
        depth: 2000,
        attack: 0.02,
        decay: 0.35,
        sustain: 0.1,
        release: 0.1,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: false, mix: 0, time: 0 },
      distortion: { isActive: true, amount: 0.8 },
      noise: { isActive: true, volume: 5 },
      lfo: { isActive: true, waveform: 'sine', frequency: 5, depth: 50, target: 'filter' },
    },
  },
  {
    id: 'preset-oxygene',
    name: 'Oxygène',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -7,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 90, detune: 7, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.3, sustain: 0.6, release: 0.4 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 800,
        resonance: 8,
        depth: 1200,
        attack: 0.05,
        decay: 0.4,
        sustain: 0.3,
        release: 0.3,
      },
      delay: { isActive: true, mix: 0.2, time: 0.3, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.3, time: 1.5 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.3, depth: 300, target: 'filter' },
    },
  },
  {
    id: 'preset-sweet-dreams',
    name: 'Sweet Dreams',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: 0,
          transpose: -12,
        },
      ],
      amplitude: { attack: 0.01, decay: 0.15, sustain: 0.8, release: 0.15 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1500,
        resonance: 4,
        depth: 0,
        attack: 0.01,
        decay: 0.1,
        sustain: 0.8,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.2, time: 0.25, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.15, time: 0.8 },
      distortion: { isActive: true, amount: 0.1 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-blue-monday',
    name: 'Blue Monday',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 90, detune: -7, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 90, detune: 7, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.3, sustain: 0.7, release: 0.3 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1200,
        resonance: 5,
        depth: 800,
        attack: 0.01,
        decay: 0.3,
        sustain: 0.4,
        release: 0.2,
      },
      delay: { isActive: true, mix: 0.3, time: 0.375, feedback: 0.4 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-tears-in-rain',
    name: 'Tears In Rain',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'triangle', volume: 80, detune: 3, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 50, detune: -3, transpose: 12 },
      ],
      amplitude: { attack: 1.2, decay: 0.5, sustain: 0.7, release: 2.0 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1200,
        resonance: 2,
        depth: 400,
        attack: 0.8,
        decay: 0.5,
        sustain: 0.5,
        release: 1.0,
      },
      delay: { isActive: true, mix: 0.4, time: 0.5, feedback: 0.4 },
      reverb: { isActive: true, mix: 0.6, time: 3.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: true, volume: 5 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.15, depth: 200, target: 'filter' },
    },
  },
  {
    id: 'preset-jump',
    name: 'Jump',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -7,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 7, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 80, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.01, decay: 0.1, sustain: 0.9, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 5000,
        resonance: 2,
        depth: 0,
        attack: 0.01,
        decay: 0.1,
        sustain: 0.9,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.15, time: 0.3, feedback: 0.25 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: true, amount: 0.15 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-on-the-run',
    name: 'On The Run',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -10,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 10,
          transpose: 0,
        },
      ],
      amplitude: { attack: 0.01, decay: 0.1, sustain: 0.8, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 2000,
        resonance: 5,
        depth: 1500,
        attack: 0.01,
        decay: 0.1,
        sustain: 0.6,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.35, time: 0.4, feedback: 0.5 },
      reverb: { isActive: true, mix: 0.25, time: 1.2 },
      distortion: { isActive: true, amount: 0.25 },
      noise: { isActive: true, volume: 8 },
      lfo: { isActive: true, waveform: 'sawtooth', frequency: 0.5, depth: 400, target: 'filter' },
    },
  },
  {
    id: 'preset-lucky-man',
    name: 'Lucky Man',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 70, detune: -5, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 70, detune: 5, transpose: 0 },
      ],
      amplitude: { attack: 0.3, decay: 0.4, sustain: 0.6, release: 1.0 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1800,
        resonance: 6,
        depth: 600,
        attack: 0.2,
        decay: 0.4,
        sustain: 0.5,
        release: 0.8,
      },
      delay: { isActive: true, mix: 0.2, time: 0.4, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.35, time: 2.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 5, depth: 30, target: 'pitch' },
    },
  },
  {
    id: 'preset-moments-in-love',
    name: 'Moments In Love',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sine', volume: 70, detune: 2, transpose: 0 },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'triangle',
          volume: 50,
          detune: -2,
          transpose: 12,
        },
      ],
      amplitude: { attack: 1.5, decay: 0.8, sustain: 0.6, release: 2.5 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 800,
        resonance: 2,
        depth: 300,
        attack: 1.0,
        decay: 0.8,
        sustain: 0.4,
        release: 2.0,
      },
      delay: { isActive: true, mix: 0.5, time: 0.6, feedback: 0.45 },
      reverb: { isActive: true, mix: 0.7, time: 4.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: true, volume: 3 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.1, depth: 150, target: 'filter' },
    },
  },
  {
    id: 'preset-axel-f',
    name: 'Axel F',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'triangle', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'square', volume: 40, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.01, decay: 0.15, sustain: 0.7, release: 0.15 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 3500,
        resonance: 3,
        depth: 0,
        attack: 0.01,
        decay: 0.1,
        sustain: 0.7,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.15, time: 0.2, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.1, time: 0.6 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-superstition',
    name: 'Superstition',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'square', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'square', volume: 60, detune: 0, transpose: 12 },
        { id: 'osc-3', isActive: true, waveform: 'square', volume: 40, detune: 0, transpose: 19 },
      ],
      amplitude: { attack: 0.01, decay: 0.01, sustain: 1.0, release: 0.05 },
      filter: {
        isActive: false,
        type: 'lowpass',
        frequency: 4000,
        resonance: 2,
        depth: 0,
        attack: 0.01,
        decay: 0.1,
        sustain: 1.0,
        release: 0.05,
      },
      delay: { isActive: false, mix: 0, time: 0.2, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.05, time: 0.4 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-popcorn',
    name: 'Popcorn',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'square', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'square', volume: 50, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.01, decay: 0.3, sustain: 0.0, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 3000,
        resonance: 3,
        depth: 0,
        attack: 0.01,
        decay: 0.2,
        sustain: 0.0,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.1, time: 0.15, feedback: 0.15 },
      reverb: { isActive: true, mix: 0.1, time: 0.5 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-thriller',
    name: 'Thriller',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'square', volume: 70, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.5, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 600,
        resonance: 6,
        depth: 1000,
        attack: 0.01,
        decay: 0.3,
        sustain: 0.2,
        release: 0.15,
      },
      delay: { isActive: true, mix: 0.1, time: 0.2, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.15, time: 0.8 },
      distortion: { isActive: true, amount: 0.2 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-computer-love',
    name: 'Computer Love',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'square', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'square', volume: 50, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.01, decay: 0.2, sustain: 0.6, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 2000,
        resonance: 3,
        depth: 500,
        attack: 0.01,
        decay: 0.2,
        sustain: 0.5,
        release: 0.15,
      },
      delay: { isActive: true, mix: 0.25, time: 0.35, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.5, depth: 200, target: 'filter' },
    },
  },
  {
    id: 'preset-running-with-the-night',
    name: 'Running With The Night',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -5,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 5, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 70, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.02, decay: 0.2, sustain: 0.8, release: 0.3 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 3000,
        resonance: 3,
        depth: 600,
        attack: 0.02,
        decay: 0.2,
        sustain: 0.7,
        release: 0.2,
      },
      delay: { isActive: true, mix: 0.25, time: 0.375, feedback: 0.35 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-dont-you-want-me',
    name: "Don't You Want Me",
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -5,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 5, transpose: 0 },
      ],
      amplitude: { attack: 0.02, decay: 0.2, sustain: 0.75, release: 0.25 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 2500,
        resonance: 3,
        depth: 400,
        attack: 0.02,
        decay: 0.2,
        sustain: 0.6,
        release: 0.2,
      },
      delay: { isActive: true, mix: 0.2, time: 0.35, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-autobahn',
    name: 'Autobahn',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 60,
          detune: 0,
          transpose: -12,
        },
      ],
      amplitude: { attack: 0.05, decay: 0.2, sustain: 0.7, release: 0.3 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1000,
        resonance: 4,
        depth: 500,
        attack: 0.05,
        decay: 0.2,
        sustain: 0.5,
        release: 0.2,
      },
      delay: { isActive: true, mix: 0.2, time: 0.3, feedback: 0.25 },
      reverb: { isActive: true, mix: 0.15, time: 0.8 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.2, depth: 100, target: 'pitch' },
    },
  },
  {
    id: 'preset-the-model',
    name: 'The Model',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'square', volume: 50, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.1, sustain: 0.8, release: 0.15 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 3000,
        resonance: 4,
        depth: 300,
        attack: 0.01,
        decay: 0.1,
        sustain: 0.7,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.15, time: 0.3, feedback: 0.25 },
      reverb: { isActive: true, mix: 0.1, time: 0.6 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 1, depth: 0, target: 'pitch' },
    },
  },
  {
    id: 'preset-finally',
    name: 'Finally',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -5,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 5, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 70, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.01, decay: 0.2, sustain: 0.8, release: 0.3 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 4000,
        resonance: 3,
        depth: 0,
        attack: 0.01,
        decay: 0.2,
        sustain: 0.8,
        release: 0.2,
      },
      delay: { isActive: true, mix: 0.2, time: 0.25, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 6, depth: 20, target: 'pitch' },
    },
  },
  {
    id: 'preset-for-the-love-of-money',
    name: 'For The Love Of Money',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: 0,
          transpose: -12,
        },
      ],
      amplitude: { attack: 0.01, decay: 0.5, sustain: 0.4, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 500,
        resonance: 8,
        depth: 1200,
        attack: 0.01,
        decay: 0.4,
        sustain: 0.2,
        release: 0.15,
      },
      delay: { isActive: true, mix: 0.1, time: 0.2, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.1, time: 0.6 },
      distortion: { isActive: true, amount: 0.35 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.8, depth: 300, target: 'filter' },
    },
  },
];
