import type { Preset } from '../stores/use-preset-store.ts';

export const DEFAULT_PRESETS: Array<Preset> = [
  {
    id: 'preset-flat-beat',
    name: 'Flat Beat',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -15,
          transpose: -12,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 15,
          transpose: -12,
        },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 80, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.2, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 150,
        resonance: 25,
        depth: 8500, // Massive sweep across the 10k range
        attack: 0.02,
        decay: 0.35,
        sustain: 0.1,
        release: 0.1,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: false, mix: 0, time: 0 },
      distortion: { isActive: true, amount: 0.8 },
      noise: { isActive: true, volume: 5 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 45, // Fast enough to add "growl"
        depth: 2000,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-da-funk',
    name: 'Da Funk',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 12,
          transpose: 0,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: -12,
          transpose: 0,
        },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 60, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.3, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 200,
        resonance: 28,
        depth: 9500, // Near maximum envelope throw
        attack: 0.01,
        decay: 0.4,
        sustain: 0.2,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.2, time: 0.3, feedback: 0.3 },
      reverb: { isActive: false, mix: 0, time: 0 },
      distortion: { isActive: true, amount: 0.9 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 120, // Audio-rate grit
        depth: 3500,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-radioactive',
    name: 'Radioactive',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -10,
          transpose: -24,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 10,
          transpose: -24,
        },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.05, decay: 0.5, sustain: 1, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 100,
        resonance: 20,
        depth: 7000,
        attack: 0.1,
        decay: 0.3,
        sustain: 1,
        release: 0.2,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: true, amount: 1.0 },
      noise: { isActive: true, volume: 15 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 4.5, // The heavy "wub" wobble
        depth: 6000,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-sandstorm',
    name: 'Sandstorm',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -25,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 25,
          transpose: 0,
        },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: true, waveform: 'sawtooth', volume: 80, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.001, decay: 0.12, sustain: 0, release: 0.05 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 800,
        resonance: 15,
        depth: 8000, // Sharp "zap" pluck
        attack: 0.001,
        decay: 0.12,
        sustain: 0,
        release: 0.05,
      },
      delay: { isActive: true, mix: 0.4, time: 0.375, feedback: 0.4 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: true, amount: 0.4 },
      noise: { isActive: true, volume: 10 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 18,
        depth: 500,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-better-off-alone',
    name: 'Better Off Alone',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -20,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 20,
          transpose: 0,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: -10,
          transpose: 12,
        },
        {
          id: 'osc-4',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: 10,
          transpose: 12,
        },
      ],
      amplitude: { attack: 0.001, decay: 0.25, sustain: 0.1, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 400,
        resonance: 10,
        depth: 8500, // Percussive trance hit
        attack: 0.001,
        decay: 0.2,
        sustain: 0.1,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.4, time: 0.375, feedback: 0.5 },
      reverb: { isActive: true, mix: 0.3, time: 2.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 6.5,
        depth: 40,
        target: 'volume',
      },
    },
  },
  {
    id: 'preset-lucky-star',
    name: 'Lucky Star',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -5,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 90, detune: 5, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 80, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 80, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.01, decay: 0.2, sustain: 0.4, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1000,
        resonance: 22,
        depth: 4000,
        attack: 0.1,
        decay: 0.2,
        sustain: 0.3,
        release: 0.2,
      },
      delay: { isActive: true, mix: 0.2, time: 0.25, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 1.8, // Disco-house filter sweep
        depth: 5500,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-blue-monday',
    name: 'Blue Monday',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
      ],
      amplitude: { attack: 0.01, decay: 0.15, sustain: 0, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 500,
        resonance: 18,
        depth: 7500,
        attack: 0,
        decay: 0.15,
        sustain: 0,
        release: 0.1,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.1, time: 0.6 },
      distortion: { isActive: true, amount: 0.2 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 110, // Audio rate for mechanical texture
        depth: 1200,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-around-the-world',
    name: 'Around the World',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 90, detune: 3, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 80, detune: 0, transpose: -12 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 80, detune: 0, transpose: -24 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.1, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 150,
        resonance: 32, // High resonance "talk"
        depth: 9800, // Full spectrum throw
        attack: 0.1,
        decay: 0.35,
        sustain: 0.05,
        release: 0.1,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: false, mix: 0, time: 0 },
      distortion: { isActive: true, amount: 0.6 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 8,
        depth: 300,
        target: 'volume',
      },
    },
  },
  {
    id: 'preset-ghostwriter',
    name: 'Ghostwriter',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -4,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 4, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.2, decay: 0.4, sustain: 0.8, release: 0.5 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 450,
        resonance: 10,
        depth: 6500,
        attack: 0.35,
        decay: 0.4,
        sustain: 0.5,
        release: 0.5,
      },
      delay: { isActive: true, mix: 0.3, time: 0.4, feedback: 0.4 },
      reverb: { isActive: true, mix: 0.4, time: 2.5 },
      distortion: { isActive: true, amount: 0.4 },
      noise: { isActive: true, volume: 20 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 7.2,
        depth: 60, // Heavy tremolo
        target: 'volume',
      },
    },
  },
  {
    id: 'preset-sicko-mode',
    name: 'Sicko Mode',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 30,
          transpose: -24,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -30,
          transpose: -24,
        },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.9, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 100,
        resonance: 25,
        depth: 9900,
        attack: 0.01,
        decay: 0.4,
        sustain: 0.05,
        release: 0.2,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.1, time: 0.5 },
      distortion: { isActive: true, amount: 1.0 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 450, // FM Style grit
        depth: 8000,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-sweet-dreams',
    name: 'Sweet Dreams',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -8,
          transpose: -12,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 8,
          transpose: -12,
        },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 90, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 70, detune: 0, transpose: -24 },
      ],
      amplitude: { attack: 0.01, decay: 0.2, sustain: 0.2, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 250,
        resonance: 15,
        depth: 7800,
        attack: 0.02,
        decay: 0.25,
        sustain: 0.1,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.1, time: 0.2, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.2, time: 0.8 },
      distortion: { isActive: true, amount: 0.3 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 140, // Industrial ringing
        depth: 1500,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-separate-ways',
    name: 'Separate Ways',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -15,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 15,
          transpose: 0,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -7,
          transpose: -12,
        },
        {
          id: 'osc-4',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 7,
          transpose: -12,
        },
      ],
      amplitude: { attack: 0.06, decay: 0.1, sustain: 0.9, release: 0.5 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 500,
        resonance: 8,
        depth: 7200,
        attack: 0.06,
        decay: 0.3,
        sustain: 0.6,
        release: 0.5,
      },
      delay: { isActive: true, mix: 0.15, time: 0.3, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.3, time: 2.0 },
      distortion: { isActive: true, amount: 3 },
      noise: { isActive: true, volume: 60 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 5.8,
        depth: 30,
        target: 'volume',
      },
    },
  },
  {
    id: 'preset-strobe',
    name: 'Strobe',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: -10,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 90, detune: 10, transpose: 0 },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: 0,
          transpose: -12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sawtooth', volume: 80, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 3.5, decay: 0.5, sustain: 1, release: 4.0 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 100,
        resonance: 6,
        depth: 8800,
        attack: 5.0,
        decay: 0.5,
        sustain: 1,
        release: 4.0,
      },
      delay: { isActive: true, mix: 0.3, time: 0.4, feedback: 0.5 },
      reverb: { isActive: true, mix: 0.6, time: 6.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: true, volume: 2 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 0.1,
        depth: 4000,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-animals',
    name: 'Animals',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 0,
          transpose: -12,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 8,
          transpose: -12,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -8,
          transpose: -12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 90, detune: 0, transpose: -24 },
      ],
      amplitude: { attack: 0.01, decay: 0.45, sustain: 0, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 50,
        resonance: 22,
        depth: 9500,
        attack: 0.01,
        decay: 0.3,
        sustain: 0,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.25, time: 0.3, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.1, time: 0.5 },
      distortion: { isActive: true, amount: 0.75 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 180, // Sizzling audio-rate modulation
        depth: 2500,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-midnight-city',
    name: 'Midnight City',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -15,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 15,
          transpose: 0,
        },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 80, detune: 0, transpose: 12 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 60, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.05, decay: 0.5, sustain: 0.6, release: 1.5 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1800,
        resonance: 5,
        depth: 4500,
        attack: 0.15,
        decay: 0.4,
        sustain: 0.7,
        release: 1.5,
      },
      delay: { isActive: true, mix: 0.35, time: 0.4, feedback: 0.45 },
      reverb: { isActive: true, mix: 0.5, time: 4.0 },
      distortion: { isActive: true, amount: 0.1 },
      noise: { isActive: true, volume: 15 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 5.5,
        depth: 80,
        target: 'volume',
      },
    },
  },
  {
    id: 'preset-heroes',
    name: 'Heroes',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: -20,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 80, detune: 20, transpose: 0 },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: -5,
          transpose: 12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sawtooth', volume: 80, detune: 5, transpose: 12 },
      ],
      amplitude: { attack: 1.0, decay: 1.0, sustain: 1, release: 2.5 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 600,
        resonance: 8,
        depth: 5500,
        attack: 1.5,
        decay: 1.0,
        sustain: 1,
        release: 2.5,
      },
      delay: { isActive: true, mix: 0.35, time: 0.5, feedback: 0.6 },
      reverb: { isActive: true, mix: 0.5, time: 4.0 },
      distortion: { isActive: true, amount: 0.3 },
      noise: { isActive: true, volume: 25 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 4.8,
        depth: 50,
        target: 'volume',
      },
    },
  },
  {
    id: 'preset-in-the-air-tonight',
    name: 'In the Air Tonight',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: -12,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 90, detune: 12, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
      ],
      amplitude: { attack: 1.2, decay: 0.5, sustain: 1, release: 2.5 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 150,
        resonance: 4,
        depth: 6000,
        attack: 1.8,
        decay: 0.5,
        sustain: 1,
        release: 2.5,
      },
      delay: { isActive: true, mix: 0.1, time: 0.4, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.4, time: 4.5 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: true, volume: 8 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 0.5,
        depth: 3500,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-baba-oriley',
    name: 'Baba O’Riley',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 6, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 80, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.01, decay: 0.1, sustain: 0, release: 0.05 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 200,
        resonance: 15,
        depth: 9200,
        attack: 0.01,
        decay: 0.1,
        sustain: 0,
        release: 0.05,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.15, time: 0.6 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 24, // Rhythmic "chopping" frequency
        depth: 8500,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-jump',
    name: 'Jump (Enhanced)',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -15,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 15,
          transpose: 0,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: 0,
          transpose: -12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 70, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.04, decay: 0.2, sustain: 0.8, release: 0.4 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 600,
        resonance: 6,
        depth: 8200,
        attack: 0.06,
        decay: 0.35,
        sustain: 0.6,
        release: 0.4,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.25, time: 1.8 },
      distortion: { isActive: true, amount: 0.15 },
      noise: { isActive: false, volume: 0 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 850, // Ultra-high sideband grit
        depth: 1200,
        target: 'filter',
      },
    },
  },
  {
    id: 'preset-1901',
    name: '1901',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -10,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 10,
          transpose: 0,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: 0,
          transpose: -12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 80, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.01, decay: 0.25, sustain: 1, release: 0.4 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1200,
        resonance: 4,
        depth: 6500,
        attack: 0.1,
        decay: 0.3,
        sustain: 0.8,
        release: 0.4,
      },
      delay: { isActive: true, mix: 0.2, time: 0.3, feedback: 0.35 },
      reverb: { isActive: true, mix: 0.25, time: 1.5 },
      distortion: { isActive: true, amount: 0.4 },
      noise: { isActive: true, volume: 5 },
      lfo: {
        isActive: true,
        waveform: 'sine',
        frequency: 1100, // Near max FM modulation
        depth: 2000,
        target: 'filter',
      },
    },
  },
];
