export const DEFAULT_PRESETS = [
  {
    id: 'preset-jump',
    name: 'Jump',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -12,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 12,
          transpose: 0,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 70,
          detune: 0,
          transpose: -12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 50, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.02, decay: 0.2, sustain: 0.8, release: 0.4 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 800,
        resonance: 6,
        depth: 0.7,
        attack: 0.05,
        decay: 0.3,
        sustain: 0.6,
        release: 0.4,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.2, time: 1.5 },
      distortion: { isActive: true, amount: 0.1 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.5, depth: 0.1, target: 'filter' },
    },
  },
  {
    id: 'preset-da-funk',
    name: 'Da Funk',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 90, detune: 10, transpose: 0 },
        { id: 'osc-3', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.3, sustain: 0.4, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 200,
        resonance: 28,
        depth: 0.95,
        attack: 0.01,
        decay: 0.4,
        sustain: 0.2,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.2, time: 0.3, feedback: 0.3 },
      reverb: { isActive: false, mix: 0, time: 0 },
      distortion: { isActive: true, amount: 0.8 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 12, depth: 0.2, target: 'filter' },
    },
  },
  {
    id: 'preset-sandstorm',
    name: 'Sandstorm',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -18,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 18,
          transpose: 0,
        },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: true, waveform: 'sawtooth', volume: 80, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.001, decay: 0.15, sustain: 0, release: 0.05 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 500,
        resonance: 10,
        depth: 0.9,
        attack: 0.001,
        decay: 0.15,
        sustain: 0,
        release: 0.05,
      },
      delay: { isActive: true, mix: 0.3, time: 0.375, feedback: 0.4 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: true, amount: 0.3 },
      noise: { isActive: true, volume: 5 },
      lfo: { isActive: false, waveform: 'sine', frequency: 0, depth: 0, target: 'volume' },
    },
  },
  {
    id: 'preset-animals',
    name: 'Animals',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 0,
          transpose: -12,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 5,
          transpose: -12,
        },
        { id: 'osc-3', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 100,
        resonance: 20,
        depth: 0.9,
        attack: 0.01,
        decay: 0.25,
        sustain: 0,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.2, time: 0.3, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.1, time: 0.5 },
      distortion: { isActive: true, amount: 0.6 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 4, depth: 0.5, target: 'filter' },
    },
  },
  {
    id: 'preset-better-off-alone',
    name: 'Better Off Alone',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -15,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 15,
          transpose: 0,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: -8,
          transpose: 12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sawtooth', volume: 80, detune: 8, transpose: 12 },
      ],
      amplitude: { attack: 0.001, decay: 0.3, sustain: 0.1, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 300,
        resonance: 12,
        depth: 0.85,
        attack: 0.001,
        decay: 0.25,
        sustain: 0.1,
        release: 0.2,
      },
      delay: { isActive: true, mix: 0.4, time: 0.375, feedback: 0.5 },
      reverb: { isActive: true, mix: 0.3, time: 2.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 6, depth: 0.05, target: 'volume' },
    },
  },
  {
    id: 'preset-blinding-lights',
    name: 'Blinding Lights',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -6,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 6, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 60, detune: 0, transpose: -12 },
        { id: 'osc-4', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.7, release: 0.4 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1200,
        resonance: 4,
        depth: 0.4,
        attack: 0.05,
        decay: 0.3,
        sustain: 0.8,
        release: 0.4,
      },
      delay: { isActive: true, mix: 0.2, time: 0.35, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.3, time: 1.5 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: true, volume: 5 },
      lfo: { isActive: true, waveform: 'sine', frequency: 5.5, depth: 0.1, target: 'volume' },
    },
  },
  {
    id: 'preset-strobe',
    name: 'Strobe',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 90, detune: -8, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 90, detune: 8, transpose: 0 },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: 0,
          transpose: -12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sawtooth', volume: 80, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 2.5, decay: 0.5, sustain: 1, release: 3.0 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 200,
        resonance: 4,
        depth: 0.8,
        attack: 4.0,
        decay: 0.5,
        sustain: 1,
        release: 3.0,
      },
      delay: { isActive: true, mix: 0.3, time: 0.4, feedback: 0.5 },
      reverb: { isActive: true, mix: 0.6, time: 5.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.15, depth: 0.4, target: 'filter' },
    },
  },
  {
    id: 'preset-ghostwriter',
    name: 'Ghostwriter',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -2,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 2, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 60, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.2, decay: 0.4, sustain: 0.8, release: 0.5 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 400,
        resonance: 8,
        depth: 0.7,
        attack: 0.3,
        decay: 0.4,
        sustain: 0.5,
        release: 0.5,
      },
      delay: { isActive: true, mix: 0.3, time: 0.4, feedback: 0.4 },
      reverb: { isActive: true, mix: 0.4, time: 2.5 },
      distortion: { isActive: true, amount: 0.3 },
      noise: { isActive: true, volume: 15 },
      lfo: { isActive: true, waveform: 'sine', frequency: 6.8, depth: 0.5, target: 'volume' },
    },
  },
  {
    id: 'preset-radioactive',
    name: 'Radioactive',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -5,
          transpose: -24,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 5,
          transpose: -24,
        },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.05, decay: 0.5, sustain: 1, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 200,
        resonance: 15,
        depth: 0.6,
        attack: 0.1,
        decay: 0.3,
        sustain: 1,
        release: 0.2,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: true, amount: 0.9 },
      noise: { isActive: true, volume: 12 },
      lfo: { isActive: true, waveform: 'sine', frequency: 3.5, depth: 0.8, target: 'filter' },
    },
  },
  {
    id: 'preset-lucky-star',
    name: 'Lucky Star',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -4,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 80, detune: 4, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 50, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 50, detune: 0, transpose: 12 },
      ],
      amplitude: { attack: 0.01, decay: 0.2, sustain: 0.5, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 800,
        resonance: 18,
        depth: 0.5,
        attack: 0.1,
        decay: 0.2,
        sustain: 0.4,
        release: 0.2,
      },
      delay: { isActive: true, mix: 0.2, time: 0.25, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.2, time: 1.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 2.0, depth: 0.6, target: 'filter' },
    },
  },
  {
    id: 'preset-sweet-dreams',
    name: 'Sweet Dreams',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -5,
          transpose: -12,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: 5,
          transpose: -12,
        },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 70, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.2, sustain: 0.2, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 300,
        resonance: 12,
        depth: 0.8,
        attack: 0,
        decay: 0.2,
        sustain: 0.1,
        release: 0.1,
      },
      delay: { isActive: true, mix: 0.1, time: 0.2, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.2, time: 0.8 },
      distortion: { isActive: true, amount: 0.2 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.5, depth: 0.1, target: 'filter' },
    },
  },
  {
    id: 'preset-around-the-world',
    name: 'Around the World',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 80, detune: 5, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 50, detune: 0, transpose: -12 },
        { id: 'osc-4', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.2, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 150,
        resonance: 30,
        depth: 0.95,
        attack: 0.08,
        decay: 0.3,
        sustain: 0.1,
        release: 0.1,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: false, mix: 0, time: 0 },
      distortion: { isActive: true, amount: 0.5 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 10, depth: 0.1, target: 'volume' },
    },
  },
  {
    id: 'preset-blue-monday',
    name: 'Blue Monday',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
        { id: 'osc-4', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.2, sustain: 0, release: 0.1 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 400,
        resonance: 15,
        depth: 0.8,
        attack: 0,
        decay: 0.15,
        sustain: 0,
        release: 0.1,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.1, time: 0.5 },
      distortion: { isActive: true, amount: 0.15 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: false, waveform: 'sine', frequency: 0, depth: 0, target: 'volume' },
    },
  },
  {
    id: 'preset-midnight-city',
    name: 'Midnight City',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -10,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 10,
          transpose: 0,
        },
        { id: 'osc-3', isActive: true, waveform: 'sawtooth', volume: 80, detune: 0, transpose: 12 },
        { id: 'osc-4', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.05, decay: 0.5, sustain: 0.6, release: 1.0 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 2500,
        resonance: 2,
        depth: 0.3,
        attack: 0.1,
        decay: 0.3,
        sustain: 0.8,
        release: 1.0,
      },
      delay: { isActive: true, mix: 0.3, time: 0.4, feedback: 0.4 },
      reverb: { isActive: true, mix: 0.5, time: 3.5 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: true, volume: 10 },
      lfo: { isActive: true, waveform: 'sine', frequency: 5.2, depth: 0.15, target: 'volume' },
    },
  },
  {
    id: 'preset-baba-oriley',
    name: 'Baba O’Riley',
    parameters: {
      oscillators: [
        { id: 'osc-1', isActive: true, waveform: 'sawtooth', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 4, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: 0 },
        { id: 'osc-4', isActive: false, waveform: 'sine', volume: 0, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.1, sustain: 0, release: 0.05 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 150,
        resonance: 10,
        depth: 0.9,
        attack: 0.01,
        decay: 0.1,
        sustain: 0,
        release: 0.05,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.1, time: 0.5 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 12.5, depth: 1.0, target: 'filter' },
    },
  },
  {
    id: 'preset-sicko-mode',
    name: 'Sicko Mode',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 25,
          transpose: -24,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -25,
          transpose: -24,
        },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
      ],
      amplitude: { attack: 0.01, decay: 0.4, sustain: 0.9, release: 0.2 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 100,
        resonance: 25,
        depth: 1.0,
        attack: 0.01,
        decay: 0.4,
        sustain: 0.1,
        release: 0.2,
      },
      delay: { isActive: false, mix: 0, time: 0, feedback: 0 },
      reverb: { isActive: true, mix: 0.1, time: 0.5 },
      distortion: { isActive: true, amount: 1.0 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 8.0, depth: 0.4, target: 'volume' },
    },
  },
  {
    id: 'preset-in-the-air-tonight',
    name: 'In the Air Tonight',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: -10,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 80, detune: 10, transpose: 0 },
        { id: 'osc-3', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -12 },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 100, detune: 0, transpose: -24 },
      ],
      amplitude: { attack: 0.8, decay: 0.5, sustain: 1, release: 2.0 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 200,
        resonance: 2,
        depth: 0.6,
        attack: 1.2,
        decay: 0.5,
        sustain: 1,
        release: 2.0,
      },
      delay: { isActive: true, mix: 0.1, time: 0.4, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.4, time: 4.0 },
      distortion: { isActive: false, amount: 0 },
      noise: { isActive: true, volume: 5 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.3, depth: 0.2, target: 'filter' },
    },
  },
  {
    id: 'preset-heroes',
    name: 'Heroes',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: -15,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 80, detune: 15, transpose: 0 },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 60,
          detune: -5,
          transpose: 12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sawtooth', volume: 60, detune: 5, transpose: 12 },
      ],
      amplitude: { attack: 0.5, decay: 1.0, sustain: 1, release: 2.0 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 800,
        resonance: 4,
        depth: 0.4,
        attack: 1.0,
        decay: 1.0,
        sustain: 1,
        release: 2.0,
      },
      delay: { isActive: true, mix: 0.3, time: 0.5, feedback: 0.6 },
      reverb: { isActive: true, mix: 0.5, time: 3.5 },
      distortion: { isActive: true, amount: 0.2 },
      noise: { isActive: true, volume: 20 },
      lfo: { isActive: true, waveform: 'sine', frequency: 4.5, depth: 0.15, target: 'volume' },
    },
  },
  {
    id: 'preset-1901',
    name: '1901',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -8,
          transpose: 0,
        },
        { id: 'osc-2', isActive: true, waveform: 'sawtooth', volume: 100, detune: 8, transpose: 0 },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 80,
          detune: 0,
          transpose: -12,
        },
        { id: 'osc-4', isActive: true, waveform: 'sine', volume: 70, detune: 0, transpose: 0 },
      ],
      amplitude: { attack: 0.01, decay: 0.2, sustain: 1, release: 0.3 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 1500,
        resonance: 2,
        depth: 0.4,
        attack: 0.05,
        decay: 0.2,
        sustain: 1,
        release: 0.3,
      },
      delay: { isActive: true, mix: 0.2, time: 0.3, feedback: 0.3 },
      reverb: { isActive: true, mix: 0.2, time: 1.2 },
      distortion: { isActive: true, amount: 0.3 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 0.2, depth: 0.1, target: 'filter' },
    },
  },
  {
    id: 'preset-separate-ways',
    name: 'Separate Ways',
    parameters: {
      oscillators: [
        {
          id: 'osc-1',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: -12,
          transpose: 0,
        },
        {
          id: 'osc-2',
          isActive: true,
          waveform: 'sawtooth',
          volume: 100,
          detune: 12,
          transpose: 0,
        },
        {
          id: 'osc-3',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: -6,
          transpose: -12,
        },
        {
          id: 'osc-4',
          isActive: true,
          waveform: 'sawtooth',
          volume: 90,
          detune: 6,
          transpose: -12,
        },
      ],
      amplitude: { attack: 0.05, decay: 0.1, sustain: 0.9, release: 0.5 },
      filter: {
        isActive: true,
        type: 'lowpass',
        frequency: 600,
        resonance: 5,
        depth: 0.75,
        attack: 0.05,
        decay: 0.3,
        sustain: 0.7,
        release: 0.5,
      },
      delay: { isActive: true, mix: 0.15, time: 0.3, feedback: 0.2 },
      reverb: { isActive: true, mix: 0.3, time: 2.0 },
      distortion: { isActive: true, amount: 0.2 },
      noise: { isActive: false, volume: 0 },
      lfo: { isActive: true, waveform: 'sine', frequency: 5.5, depth: 0.05, target: 'volume' },
    },
  },
];
